In [3]:
import numpy as np

In [4]:
# создание матрицы а 4х4 со случайными числами
a = np.array([[8, 3, 1, 4], [3, 7, 1, 2], [0, 9, 2, 10], [2, 5, 2, 9]])
a

array([[ 8,  3,  1,  4],
       [ 3,  7,  1,  2],
       [ 0,  9,  2, 10],
       [ 2,  5,  2,  9]])

In [5]:
# размеры матрицы
a.shape

(4, 4)

In [8]:
# вывод типа данных элементов матрицы
a.dtype

dtype('int64')

In [9]:
# создание единичной матрицы
eye = np.eye(4)
eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
# поэлементное умножение матриц
a * eye

array([[8., 0., 0., 0.],
       [0., 7., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 9.]])

In [22]:
# агрегация
print(a.max(), a.min(), a.mean())

99 13 51.25


In [23]:
# вывод элемента матрицы по индексу
print(a[2][1])

22


In [24]:
# срез
a[1:3]

array([[85, 73, 33, 17],
       [18, 22, 50, 59]], dtype=int32)

In [28]:
# срез строки матрицы
a[3][0:2]

array([87, 99], dtype=int32)

In [39]:
# Изменение формы
a.ravel()

array([13, 32, 40, 47, 85, 73, 33, 17, 18, 22, 50, 59, 87, 99, 76, 69],
      dtype=int32)

In [40]:
a.reshape(2, 8)

array([[13, 32, 40, 47, 85, 73, 33, 17],
       [18, 22, 50, 59, 87, 99, 76, 69]], dtype=int32)

In [41]:
# Объединение матриц
np.hstack((a, eye))

array([[13., 32., 40., 47.,  1.,  0.,  0.,  0.],
       [85., 73., 33., 17.,  0.,  1.,  0.,  0.],
       [18., 22., 50., 59.,  0.,  0.,  1.,  0.],
       [87., 99., 76., 69.,  0.,  0.,  0.,  1.]])